"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Loader2, Wand2, AlertTriangle, ArrowRight, Check } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { useAuth } from "@/hooks/use-auth";
import { translateDbError } from "@/lib/utils";
import { toast } from "sonner";
import { generateSchedule } from "@/lib/schedule-generator";
import { MONTHS } from "@/lib/constants";
import { useSettings } from "@/hooks/use-settings";
import { dayOfWeek, isHoliday, isNightShift } from "@/lib/equity-helpers";
import type {
  Profile,
  ProfileWithPositions,
  ShiftTemplate,
  Position,
  Schedule,
  ScheduleEntry,
  StaffingRequirement,
  AutoGenResult,
  AutoGenWarning,
  ContractType,
  HolidayDate,
  EmployeeEquityRollup,
  ScoringWeights,
  RestRule,
  EmployeeRestRule,
} from "@/lib/types";

const defaultWeights: ScoringWeights = {
  sunday_penalty: 20,
  saturday_penalty: 15,
  night_penalty: 12,
  holiday_penalty: 18,
  block_continuation_bonus: 15,
  fragmentation_penalty: 25,
  clean_restart_bonus: 5,
  position_primary_bonus: 100,
  position_secondary_bonus: 30,
  hour_deficit_multiplier: 10,
  shift_deficit_multiplier: 5,
};

const CAPACITY_OK_THRESHOLD = 1; // supply >= demand
const CAPACITY_WARN_THRESHOLD = 0.6; // supply covers >= 60% of estimated demand
const EQUITY_BALANCED_THRESHOLD_HOURS = 2; // stddev below this reads as "balanced"

type WarningGroup = {
  kind: AutoGenWarning["kind"];
  count: number;
  affectedPositions: Set<string>;
};

function groupWarnings(warnings: AutoGenWarning[]): WarningGroup[] {
  const map = new Map<AutoGenWarning["kind"], WarningGroup>();
  for (const w of warnings) {
    let g = map.get(w.kind);
    if (!g) {
      g = { kind: w.kind, count: 0, affectedPositions: new Set() };
      map.set(w.kind, g);
    }
    g.count++;
    if ("positionId" in w) g.affectedPositions.add(w.positionId);
  }
  return Array.from(map.values()).sort((a, b) => b.count - a.count);
}

function eligibleEmployeeCount(
  positionId: string,
  employees: Profile[],
  secondaryMap: Map<string, Set<string>>
): number {
  let n = 0;
  for (const e of employees) {
    if (e.position_id === positionId) n++;
    else if (secondaryMap.get(e.id)?.has(positionId)) n++;
  }
  return n;
}

interface AutoGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  schedule: Schedule;
  employees: Profile[];
  shiftTemplates: ShiftTemplate[];
  positions: Position[];
  existingEntries: ScheduleEntry[];
  month: number;
  year: number;
  locationName: string;
  contractTypes: ContractType[];
  holidays: HolidayDate[];
  rollups: EmployeeEquityRollup[];
  scoringWeights: ScoringWeights | null;
  onGenerated: () => void;
}

export function AutoGenerateDialog({
  open,
  onOpenChange,
  schedule,
  employees,
  shiftTemplates,
  positions,
  existingEntries,
  month,
  year,
  locationName,
  contractTypes,
  holidays,
  rollups,
  scoringWeights,
  onGenerated,
}: AutoGenerateDialogProps) {
  const supabase = createClient();
  const { effectiveOrgId } = useAuth();
  const { constraints, loading: constraintsLoading } = useSettings();
  const router = useRouter();
  const [generating, setGenerating] = useState(false);
  const [applying, setApplying] = useState(false);
  const [result, setResult] = useState<AutoGenResult | null>(null);

  // Selection state: all selected by default
  const [selTemplates, setSelTemplates] = useState<Set<string>>(
    new Set(shiftTemplates.map((t) => t.id))
  );
  const [selPositions, setSelPositions] = useState<Set<string>>(
    new Set(positions.map((p) => p.id))
  );
  const [selEmployees, setSelEmployees] = useState<Set<string>>(
    new Set(employees.map((e) => e.id))
  );

  // Demand mode
  const [useDemand, setUseDemand] = useState(false);
  const [staffingReqs, setStaffingReqs] = useState<StaffingRequirement[]>([]);
  const [hasStaffingConfig, setHasStaffingConfig] = useState(false);

  // Fetch staffing requirements on open
  useEffect(() => {
    if (!open) return;
    async function fetchStaffing() {
      const { data } = await supabase
        .from("staffing_requirements")
        .select("*")
        .eq("location_id", schedule.location_id);
      const reqs = (data ?? []) as StaffingRequirement[];
      setStaffingReqs(reqs);
      const hasConfig = reqs.length > 0;
      setHasStaffingConfig(hasConfig);
      setUseDemand(hasConfig);
    }
    fetchStaffing();
  }, [open, supabase, schedule.location_id]);

  const [secondaryMap, setSecondaryMap] = useState<Map<string, Set<string>>>(new Map());

  useEffect(() => {
    if (!open) return;
    async function fetchSecondary() {
      const { data } = await supabase
        .from("employee_secondary_positions")
        .select("employee_id, position_id")
        .in("employee_id", employees.map((e) => e.id));
      const m = new Map<string, Set<string>>();
      for (const row of data ?? []) {
        if (!m.has(row.employee_id)) m.set(row.employee_id, new Set());
        m.get(row.employee_id)!.add(row.position_id);
      }
      setSecondaryMap(m);
      setSelPositions((prev) => {
        const next = new Set<string>();
        for (const id of Array.from(prev)) {
          const eligibles = employees.filter(
            (e) => e.position_id === id || m.get(e.id)?.has(id)
          ).length;
          if (eligibles > 0) next.add(id);
        }
        return next;
      });
    }
    fetchSecondary();
  }, [open, supabase, employees]);

  // Reset when dialog opens
  function handleOpenChange(isOpen: boolean) {
    if (isOpen) {
      setResult(null);
      setSelTemplates(new Set(shiftTemplates.map((t) => t.id)));
      setSelPositions(new Set(positions.map((p) => p.id)));
      setSelEmployees(new Set(employees.map((e) => e.id)));
    }
    onOpenChange(isOpen);
  }

  function navigateAndClose(path: string) {
    onOpenChange(false);
    router.push(path);
  }

  function toggleSet(set: Set<string>, id: string): Set<string> {
    const next = new Set(set);
    if (next.has(id)) next.delete(id);
    else next.add(id);
    return next;
  }

  async function handleGenerate() {
    setGenerating(true);

    // Fetch approved time-off for selected employees
    const { data: timeOff } = await supabase
      .from("time_off_requests")
      .select("employee_id, start_date, end_date")
      .eq("status", "approved")
      .in("employee_id", Array.from(selEmployees));

    // Fetch rest rules: contract-level (default) + employee-level (override)
    const [{ data: rulesData }, { data: empRulesData }] = await Promise.all([
      supabase.from("contract_rest_rules").select("*"),
      supabase.from("employee_rest_rules").select("*").in("employee_id", Array.from(selEmployees)),
    ]);
    const restRules = (rulesData ?? []) as unknown as RestRule[];
    const employeeRestRules = (empRulesData ?? []) as unknown as EmployeeRestRule[];

    // Fetch employees with secondary positions
    const { data: secondaryData } = await supabase
      .from("employee_secondary_positions")
      .select("employee_id, position_id")
      .in("employee_id", Array.from(selEmployees));

    // Build ProfileWithPositions
    const secondaryMap = new Map<string, { employee_id: string; position_id: string; id: string; created_at: string }[]>();
    for (const sp of secondaryData ?? []) {
      if (!secondaryMap.has(sp.employee_id)) secondaryMap.set(sp.employee_id, []);
      secondaryMap.get(sp.employee_id)!.push({
        id: "",
        employee_id: sp.employee_id,
        position_id: sp.position_id,
        created_at: "",
      });
    }

    const employeesWithPositions: ProfileWithPositions[] = employees
      .filter((e) => selEmployees.has(e.id))
      .map((e) => ({
        ...e,
        secondary_positions: secondaryMap.get(e.id) ?? [],
      }));

    // When demand mode is on, gather position IDs from staffing requirements
    const positionIds = useDemand
      ? Array.from(new Set(staffingReqs.map((r) => r.position_id)))
      : Array.from(selPositions);

    const genResult = generateSchedule(
      {
        scheduleId: schedule.id,
        locationId: schedule.location_id,
        month,
        year,
        shiftTemplateIds: Array.from(selTemplates),
        positionIds,
        excludeDates: [],
        employeeIds: Array.from(selEmployees),
        useDemandRequirements: useDemand,
      },
      employeesWithPositions,
      shiftTemplates,
      existingEntries,
      timeOff || [],
      constraints,
      staffingReqs,
      rollups,
      holidays,
      contractTypes,
      scoringWeights ?? defaultWeights,
      restRules,
      employeeRestRules,
    );

    setResult(genResult);
    setGenerating(false);
  }

  async function handleApply() {
    if (!result || result.entries.length === 0) return;
    setApplying(true);

    const entriesWithOrg = result.entries.map((e) => ({
      ...e,
      organization_id: effectiveOrgId ?? "",
    }));
    const { error } = await supabase
      .from("schedule_entries")
      .insert(entriesWithOrg);

    if (error) {
      toast.error(translateDbError(error.message, "Error al insertar turnos"));
    } else {
      toast.success(`${result.entries.length} turnos generados correctamente`);
      onOpenChange(false);
      onGenerated();
    }
    setApplying(false);
  }

  // Compute equity metric (standard deviation of hours)
  function computeEquityStdDev(): string {
    if (!result) return "";
    const hourValues = Object.values(result.stats)
      .filter((v) => v.shifts > 0)
      .map((v) => v.hours);
    if (hourValues.length < 2) return "";
    const mean = hourValues.reduce((a, b) => a + b, 0) / hourValues.length;
    const variance = hourValues.reduce((sum, h) => sum + (h - mean) ** 2, 0) / hourValues.length;
    const stdDev = Math.sqrt(variance);
    return stdDev.toFixed(1);
  }

  // Map: positionId → { deptKey, deptLabel } based on the position's department.
  const positionToDept = useMemo(() => {
    const m = new Map<string, { key: string; label: string }>();
    for (const p of positions) {
      const dep = (p.department as { id?: string; name?: string } | undefined) ?? null;
      m.set(p.id, {
        key: dep?.id ?? "__sin_dept__",
        label: dep?.name ?? "Sin departamento",
      });
    }
    return m;
  }, [positions]);

  // Map: templateId → Set<positionId> (which positions this template covers in staffing)
  const templateToPositions = useMemo(() => {
    const m = new Map<string, Set<string>>();
    for (const sr of staffingReqs) {
      if (!m.has(sr.shift_template_id)) m.set(sr.shift_template_id, new Set());
      m.get(sr.shift_template_id)!.add(sr.position_id);
    }
    return m;
  }, [staffingReqs]);

  // Map: templateId → Set<deptKey> (derived from templateToPositions + positionToDept)
  const templateToDepts = useMemo(() => {
    const m = new Map<string, Set<string>>();
    templateToPositions.forEach((posIds, tplId) => {
      const set = new Set<string>();
      for (const pid of Array.from(posIds)) {
        const dep = positionToDept.get(pid);
        if (dep) set.add(dep.key);
      }
      m.set(tplId, set);
    });
    return m;
  }, [templateToPositions, positionToDept]);

  // Department options derived from positions (consistent with grid filter)
  const departmentOptions = useMemo(() => {
    const map = new Map<string, string>();
    for (const dep of Array.from(positionToDept.values())) {
      if (!map.has(dep.key)) map.set(dep.key, dep.label);
    }
    return Array.from(map.entries())
      .map(([key, label]) => ({ key, label }))
      .sort((a, b) => {
        if (a.key === "__sin_dept__") return 1;
        if (b.key === "__sin_dept__") return -1;
        return a.label.localeCompare(b.label, "es");
      });
  }, [positionToDept]);

  // Group templates by department. A template that touches multiple depts goes under
  // the "Multi-departamento" pseudo-group; one with no staffing usage goes under "Sin uso".
  const MULTI_KEY = "__multi__";
  const NO_USE_KEY = "__no_use__";
  const templateGroups = useMemo(() => {
    type Group = { key: string; label: string; templates: ShiftTemplate[] };
    const map = new Map<string, Group>();
    for (const tpl of shiftTemplates) {
      const depts = Array.from(templateToDepts.get(tpl.id) ?? new Set<string>());
      let key: string;
      let label: string;
      if (depts.length === 0) {
        key = NO_USE_KEY;
        label = "Sin uso en necesidades";
      } else if (depts.length === 1) {
        key = depts[0];
        label = departmentOptions.find((d) => d.key === key)?.label ?? "Departamento";
      } else {
        key = MULTI_KEY;
        label = "Multi-departamento";
      }
      if (!map.has(key)) map.set(key, { key, label, templates: [] });
      map.get(key)!.templates.push(tpl);
    }
    const arr = Array.from(map.values());
    arr.sort((a, b) => {
      // Real departments first (alphabetical), then Multi, then Sin uso
      const order = (k: string) =>
        k === MULTI_KEY ? 1 : k === NO_USE_KEY ? 2 : 0;
      const oa = order(a.key);
      const ob = order(b.key);
      if (oa !== ob) return oa - ob;
      return a.label.localeCompare(b.label, "es");
    });
    for (const g of arr) g.templates.sort((a, b) => a.name.localeCompare(b.name, "es"));
    return arr;
  }, [shiftTemplates, templateToDepts, departmentOptions]);

  // Eligible employees = union of (primary or secondary in any position covered by
  // any selected template). Used to dim non-applicable employees in the list.
  const eligibleEmployeeIds = useMemo(() => {
    if (selTemplates.size === 0) return new Set<string>();
    const relevantPositions = new Set<string>();
    for (const tplId of Array.from(selTemplates)) {
      const ps = templateToPositions.get(tplId);
      if (ps) for (const pid of Array.from(ps)) relevantPositions.add(pid);
    }
    // If no staffing config exists yet, fall back to "all employees are eligible".
    if (relevantPositions.size === 0) return new Set(employees.map((e) => e.id));

    const eligible = new Set<string>();
    for (const e of employees) {
      if (e.position_id && relevantPositions.has(e.position_id)) {
        eligible.add(e.id);
        continue;
      }
      const sec = secondaryMap.get(e.id);
      if (sec) {
        for (const pid of Array.from(sec)) {
          if (relevantPositions.has(pid)) {
            eligible.add(e.id);
            break;
          }
        }
      }
    }
    return eligible;
  }, [selTemplates, templateToPositions, employees, secondaryMap]);

  // Group employees by department of their primary position
  const employeeGroups = useMemo(() => {
    type Group = { key: string; label: string; employees: Profile[] };
    const map = new Map<string, Group>();
    for (const e of employees) {
      const dep = e.position_id ? positionToDept.get(e.position_id) : null;
      const key = dep?.key ?? "__sin_dept__";
      const label = dep?.label ?? "Sin departamento";
      if (!map.has(key)) map.set(key, { key, label, employees: [] });
      map.get(key)!.employees.push(e);
    }
    const arr = Array.from(map.values());
    arr.sort((a, b) => {
      if (a.key === "__sin_dept__") return 1;
      if (b.key === "__sin_dept__") return -1;
      return a.label.localeCompare(b.label, "es");
    });
    for (const g of arr) {
      g.employees.sort((a, b) => {
        const ln = (a.last_name ?? "").localeCompare(b.last_name ?? "", "es");
        if (ln !== 0) return ln;
        return (a.first_name ?? "").localeCompare(b.first_name ?? "", "es");
      });
    }
    return arr;
  }, [employees, positionToDept]);

  function applyOnlyEligible() {
    setSelEmployees(new Set(Array.from(eligibleEmployeeIds)));
  }

  function applyOnlyOneTemplate(tplId: string) {
    setSelTemplates(new Set([tplId]));
    // Restrict positions to those covered by the template (if staffing config exists)
    const ps = templateToPositions.get(tplId);
    if (ps && ps.size > 0) {
      setSelPositions(new Set(Array.from(ps)));
    }
    // Auto-select only eligible employees for that template
    const relevant = new Set<string>();
    if (ps) {
      for (const e of employees) {
        if (e.position_id && ps.has(e.position_id)) {
          relevant.add(e.id);
          continue;
        }
        const sec = secondaryMap.get(e.id);
        if (sec) {
          for (const pid of Array.from(sec)) {
            if (ps.has(pid)) {
              relevant.add(e.id);
              break;
            }
          }
        }
      }
      setSelEmployees(relevant);
    }
  }

  const capacity = useMemo(() => {
    const selectedEmps = employees.filter((e) => selEmployees.has(e.id));
    const selectedTpls = shiftTemplates.filter((t) => selTemplates.has(t.id));
    if (selectedEmps.length === 0 || selectedTpls.length === 0) return null;

    const daysInMonth = new Date(year, month + 1, 0).getDate();
    const weeksInMonth = daysInMonth / 7;

    // Supply: sum of min(constraint, emp cap) weekly hours × weeks
    const weeklyCap = selectedEmps.reduce(
      (sum, e) => sum + Math.min(constraints.maxHoursPerWeek, e.max_hours_per_week),
      0
    );
    const supplyHours = weeklyCap * weeksInMonth;

    // Demand: N positions × N templates × daysInMonth × avg template hours (fallback mode)
    const avgTplHours =
      selectedTpls.reduce((s, t) => {
        const [sh, sm] = t.start_time.split(":").map(Number);
        const [eh, em] = t.end_time.split(":").map(Number);
        let min = eh * 60 + em - (sh * 60 + sm);
        if (min < 0) min += 24 * 60;
        return s + (min - t.break_minutes) / 60;
      }, 0) / selectedTpls.length;

    const slots = useDemand
      ? 0 // cannot cheaply estimate demand-mode; skip in that case
      : selPositions.size * selectedTpls.length * daysInMonth;
    const demandHours = slots * avgTplHours;

    if (slots === 0) return null;
    const ratio = supplyHours / demandHours;
    return { supplyHours, demandHours, slots, ratio };
  }, [employees, selEmployees, shiftTemplates, selTemplates, selPositions, useDemand, constraints, year, month]);

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="max-w-lg max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Wand2 className="h-5 w-5" />
            Auto-generar horario
          </DialogTitle>
          <DialogDescription className="space-y-0.5">
            <span className="block">
              {MONTHS[month]} {year} · Sede: <span className="font-medium text-foreground">{locationName}</span>
            </span>
            <span className="block text-xs">
              {selEmployees.size} empleados seleccionados · {selTemplates.size} plantillas · {useDemand ? "modo demanda" : `${selPositions.size} posiciones`}
            </span>
          </DialogDescription>
        </DialogHeader>

        {!result ? (
          /* Configuration step */
          <div className="space-y-4 py-2">
            {/* Demand mode toggle */}
            {hasStaffingConfig && (
              <div className="flex items-center gap-2 rounded-md border p-3 bg-muted/50">
                <input
                  type="checkbox"
                  id="demand-mode"
                  checked={useDemand}
                  onChange={(e) => setUseDemand(e.target.checked)}
                  className="h-4 w-4 rounded"
                />
                <div>
                  <Label htmlFor="demand-mode" className="cursor-pointer text-sm font-medium">
                    Usar necesidades de personal
                  </Label>
                  <p className="text-xs text-muted-foreground">
                    Genera turnos basado en la demanda configurada por posición, turno y día
                  </p>
                </div>
              </div>
            )}

            {/* Quick shortcut: regenerate only one plantilla */}
            {shiftTemplates.length > 1 && (
              <div className="rounded-md border bg-muted/40 px-3 py-2">
                <div className="text-xs text-muted-foreground mb-1.5">
                  Atajo · regenerar solo una plantilla
                </div>
                <select
                  value=""
                  onChange={(e) => {
                    if (e.target.value) {
                      applyOnlyOneTemplate(e.target.value);
                      e.target.value = "";
                    }
                  }}
                  className="w-full rounded-md border border-input bg-background px-2 py-1.5 text-sm"
                >
                  <option value="">Seleccionar plantilla…</option>
                  {templateGroups.map((g) => (
                    <optgroup key={g.key} label={g.label}>
                      {g.templates.map((t) => (
                        <option key={t.id} value={t.id}>
                          {t.name}
                        </option>
                      ))}
                    </optgroup>
                  ))}
                </select>
              </div>
            )}

            {/* Templates — grouped by department */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label>
                  Plantillas de turno ({selTemplates.size}/{shiftTemplates.length})
                </Label>
                <div className="flex gap-2 text-xs">
                  <button
                    type="button"
                    onClick={() => setSelTemplates(new Set(shiftTemplates.map((t) => t.id)))}
                    className="text-primary hover:underline"
                  >
                    Todas
                  </button>
                  <span className="text-muted-foreground">·</span>
                  <button
                    type="button"
                    onClick={() => setSelTemplates(new Set())}
                    className="text-primary hover:underline"
                  >
                    Ninguna
                  </button>
                </div>
              </div>
              <div className="space-y-2">
                {templateGroups.map((g) => {
                  const groupIds = g.templates.map((t) => t.id);
                  const groupSelectedCount = groupIds.filter((id) => selTemplates.has(id)).length;
                  const allOn = groupSelectedCount === groupIds.length && groupIds.length > 0;
                  return (
                    <div key={g.key} className="rounded-md border bg-card px-2.5 py-2">
                      <div className="flex items-center justify-between mb-1.5">
                        <div className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
                          {g.label}{" "}
                          <span className="ml-1 font-normal text-muted-foreground/70">
                            {groupSelectedCount}/{groupIds.length}
                          </span>
                        </div>
                        <button
                          type="button"
                          onClick={() => {
                            const next = new Set(selTemplates);
                            if (allOn) {
                              for (const id of groupIds) next.delete(id);
                            } else {
                              for (const id of groupIds) next.add(id);
                            }
                            setSelTemplates(next);
                          }}
                          className="text-[10px] text-primary hover:underline"
                        >
                          {allOn ? "Ninguna" : "Todas"}
                        </button>
                      </div>
                      <div className="flex flex-wrap gap-1.5">
                        {g.templates.map((t) => (
                          <button
                            key={t.id}
                            type="button"
                            onClick={() => setSelTemplates(toggleSet(selTemplates, t.id))}
                            className={`rounded-full px-2.5 py-0.5 text-xs font-medium border transition-colors ${
                              selTemplates.has(t.id)
                                ? "bg-primary text-primary-foreground border-primary"
                                : "bg-background text-muted-foreground border-border"
                            }`}
                          >
                            {t.name}
                          </button>
                        ))}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Positions — hide when demand mode is on since positions come from requirements */}
            {!useDemand && (
              <div className="space-y-2">
                <Label>Posiciones</Label>
                <div className="flex flex-wrap gap-2">
                  {positions.map((p) => {
                    const dept = (p.department as { name?: string } | undefined)?.name;
                    const selected = selPositions.has(p.id);
                    const eligibles = eligibleEmployeeCount(p.id, employees, secondaryMap);
                    const disabled = eligibles === 0;
                    return (
                      <button
                        key={p.id}
                        type="button"
                        disabled={disabled}
                        title={disabled ? "Sin empleados asignados" : undefined}
                        onClick={() => {
                          if (disabled) return;
                          setSelPositions(toggleSet(selPositions, p.id));
                        }}
                        className={`rounded-lg px-3 py-2 text-xs font-medium border transition-colors text-left ${
                          disabled
                            ? "bg-muted text-muted-foreground/50 border-dashed border-border cursor-not-allowed"
                            : selected
                            ? "border-transparent text-white"
                            : "bg-background text-muted-foreground border-border"
                        }`}
                        style={!disabled && selected ? { backgroundColor: p.color } : undefined}
                      >
                        <div>{p.name}</div>
                        <div className={`text-[10px] ${selected && !disabled ? "opacity-80" : "text-muted-foreground/70"}`}>
                          {dept ? `${dept} · ` : ""}
                          {disabled ? "sin empleados" : `${eligibles} elegibles`}
                        </div>
                      </button>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Employees — grouped by department, with smart eligibility hints */}
            <div className="space-y-2">
              <div className="flex flex-wrap items-center justify-between gap-1">
                <Label>
                  Empleados ({selEmployees.size}/{employees.length})
                  {eligibleEmployeeIds.size > 0 && eligibleEmployeeIds.size < employees.length && (
                    <span className="ml-1 text-[11px] font-normal text-muted-foreground">
                      · {eligibleEmployeeIds.size} elegibles para las plantillas seleccionadas
                    </span>
                  )}
                </Label>
                <div className="flex gap-2 text-xs">
                  <button
                    type="button"
                    onClick={applyOnlyEligible}
                    disabled={eligibleEmployeeIds.size === 0 || eligibleEmployeeIds.size === employees.length}
                    className="text-primary hover:underline disabled:cursor-default disabled:opacity-40 disabled:no-underline"
                  >
                    Solo elegibles
                  </button>
                  <span className="text-muted-foreground">·</span>
                  <button
                    type="button"
                    onClick={() => setSelEmployees(new Set(employees.map((e) => e.id)))}
                    className="text-primary hover:underline"
                  >
                    Todos
                  </button>
                  <span className="text-muted-foreground">·</span>
                  <button
                    type="button"
                    onClick={() => setSelEmployees(new Set())}
                    className="text-primary hover:underline"
                  >
                    Ninguno
                  </button>
                </div>
              </div>
              <div className="max-h-64 overflow-y-auto rounded border p-2 space-y-3">
                {employeeGroups.map((g) => {
                  const groupIds = g.employees.map((e) => e.id);
                  const groupSelectedCount = groupIds.filter((id) => selEmployees.has(id)).length;
                  const allOn = groupSelectedCount === groupIds.length && groupIds.length > 0;
                  return (
                    <div key={g.key}>
                      <div className="flex items-center justify-between mb-1 sticky top-0 bg-card/95 backdrop-blur supports-[backdrop-filter]:bg-card/60 -mx-2 px-2 py-0.5">
                        <div className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
                          {g.label}{" "}
                          <span className="ml-1 font-normal text-muted-foreground/70">
                            {groupSelectedCount}/{groupIds.length}
                          </span>
                        </div>
                        <button
                          type="button"
                          onClick={() => {
                            const next = new Set(selEmployees);
                            if (allOn) {
                              for (const id of groupIds) next.delete(id);
                            } else {
                              for (const id of groupIds) next.add(id);
                            }
                            setSelEmployees(next);
                          }}
                          className="text-[10px] text-primary hover:underline"
                        >
                          {allOn ? "Ninguno" : "Todos"}
                        </button>
                      </div>
                      <div className="space-y-0.5">
                        {g.employees.map((e) => {
                          const primary = positions.find((p) => p.id === e.position_id);
                          const eligible = eligibleEmployeeIds.has(e.id);
                          const checked = selEmployees.has(e.id);
                          return (
                            <label
                              key={e.id}
                              className={`flex items-center gap-2 text-sm cursor-pointer py-1 rounded px-1 hover:bg-muted/40 ${
                                !eligible ? "opacity-50" : ""
                              }`}
                              title={!eligible ? "No cubre ninguna posición de las plantillas seleccionadas" : undefined}
                            >
                              <input
                                type="checkbox"
                                checked={checked}
                                onChange={() =>
                                  setSelEmployees(toggleSet(selEmployees, e.id))
                                }
                                className="rounded"
                              />
                              <div className="flex-1 min-w-0">
                                <div className="truncate flex items-center gap-1">
                                  <span className={e.is_demo ? "italic" : ""}>
                                    {e.first_name} {e.last_name}
                                  </span>
                                  {e.is_demo && (
                                    <span className="text-[10px] text-amber-600">(demo)</span>
                                  )}
                                  {e.is_floater && (
                                    <span className="text-[10px] text-blue-600">(super)</span>
                                  )}
                                  {!eligible && (
                                    <span className="text-[10px] text-muted-foreground/80">
                                      · no aplica
                                    </span>
                                  )}
                                </div>
                                <div className="text-[11px] text-muted-foreground truncate">
                                  {primary ? primary.name : "Sin posición"}
                                  {" · "}
                                  {e.max_hours_per_week}h/sem
                                </div>
                              </div>
                            </label>
                          );
                        })}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Pre-flight capacity estimate */}
            {(() => {
              const cap = capacity;
              if (!cap) return null;
              const pct = Math.round(cap.ratio * 100);
              const tone =
                cap.ratio >= CAPACITY_OK_THRESHOLD
                  ? "border-emerald-200 bg-emerald-50 text-emerald-800"
                  : cap.ratio >= CAPACITY_WARN_THRESHOLD
                  ? "border-amber-200 bg-amber-50 text-amber-800"
                  : "border-red-200 bg-red-50 text-red-800";
              return (
                <div className={`rounded border p-2 text-xs ${tone}`}>
                  <div className="font-medium">
                    {cap.ratio >= CAPACITY_OK_THRESHOLD
                      ? `Capacidad suficiente (${pct}%)`
                      : `Cobertura estimada: ${pct}%`}
                  </div>
                  <div className="opacity-80">
                    Estimado: {cap.slots} ranuras (~{Math.round(cap.demandHours)}h) vs {Math.round(cap.supplyHours)}h disponibles.
                    {cap.ratio < CAPACITY_OK_THRESHOLD && " Sumar personal o reducir plantillas."}
                    <span className="block mt-0.5 opacity-70">
                      Supuesto: 1 persona por posición × plantilla × día. La demanda real puede ser menor.
                    </span>
                  </div>
                </div>
              );
            })()}

            {/* Constraints info */}
            {!constraintsLoading && (
              <div className="text-xs text-muted-foreground rounded border p-2">
                <span className="font-medium">Restricciones:</span>{" "}
                Max {constraints.maxHoursPerWeek}h/sem, {constraints.maxHoursPerDay}h/día,{" "}
                {constraints.minRestHoursBetweenShifts}h descanso, {constraints.maxConsecutiveDays} dias consecutivos max
              </div>
            )}
          </div>
        ) : (
          /* Results step */
          (() => {
            // Compute D/S/N/F breakdown per employee
            const perEmpBreakdown = new Map<
              string,
              { D: number; S: number; N: number; F: number }
            >();
            for (const e of result.entries) {
              const b = perEmpBreakdown.get(e.employee_id) ?? {
                D: 0,
                S: 0,
                N: 0,
                F: 0,
              };
              const dow = dayOfWeek(e.date);
              if (dow === 0) b.D++;
              if (dow === 6) b.S++;
              const tpl = shiftTemplates.find(
                (t) => t.id === e.shift_template_id
              );
              if (tpl && isNightShift(tpl)) b.N++;
              if (isHoliday(e.date, schedule.location_id, holidays)) b.F++;
              perEmpBreakdown.set(e.employee_id, b);
            }

            const normals = result.entries.filter(
              (e) => e.overtime_status === "none"
            ).length;
            const overtimePending = result.entries.filter(
              (e) => e.overtime_status === "pending"
            ).length;
            const totalEntries = result.entries.length;

            const hasNoStaffing = result.warnings.some(
              (w) => w.kind === "no_employees_in_position"
            );
            const noShiftsAtAll = totalEntries === 0 && result.warnings.length === 0;

            return (
          /* Superficie de resultados de la generación async: live region "polite"
             (role="status") para que un lector de pantalla anuncie el resumen de
             cobertura y las advertencias cuando terminan de calcularse. Urgencia
             estándar (banner/resultado), no assertive. Guía modern-web-guidance:
             accessibility §8 (Live Regions). */
          <div className="space-y-4 py-2" role="status" aria-live="polite">
            {noShiftsAtAll && (
              <div className="rounded-md border border-amber-300 bg-amber-50 p-3 space-y-2">
                <p className="text-sm font-medium text-amber-900">
                  No se generaron turnos
                </p>
                <p className="text-xs text-amber-800">
                  Las posiciones de los empleados seleccionados no tienen necesidades configuradas. Configurá primero la demanda en{" "}
                  <Link href="/staffing" className="underline font-medium">
                    Necesidades
                  </Link>
                  {" "}y volvé a generar.
                </p>
              </div>
            )}
            {hasNoStaffing && totalEntries === 0 && !noShiftsAtAll && (
              <div className="rounded-md border border-amber-300 bg-amber-50 p-3 space-y-2">
                <p className="text-sm font-medium text-amber-900">
                  No hay candidatos para las necesidades configuradas
                </p>
                <p className="text-xs text-amber-800">
                  Verificá que los empleados seleccionados tengan la posición correcta y que las plantillas de turno coincidan con lo configurado en{" "}
                  <Link href="/staffing" className="underline font-medium">
                    Necesidades
                  </Link>
                  .
                </p>
              </div>
            )}
            <div className="rounded-md bg-muted p-3 space-y-1">
              <p className="font-medium text-sm">{totalEntries} turnos generados</p>
              {overtimePending > 0 && (
                <p className="text-xs text-amber-700">
                  {normals} normales ·{" "}
                  <span className="font-medium">
                    {overtimePending} con horas extra (pendientes de aprobación)
                  </span>
                </p>
              )}
            </div>

            <div className="rounded-md bg-muted p-3 space-y-1">
              {(() => {
                const filled = result.entries.length;
                const unfilled = result.warnings.filter(
                  (w) =>
                    w.kind === "no_employees_in_position" ||
                    w.kind === "no_safe_candidate" ||
                    w.kind === "holiday_hours_exceed_cap"
                ).length;
                const total = filled + unfilled;
                const pct = total > 0 ? Math.round((filled / total) * 100) : 100;
                return (
                  <>
                    <p className="font-medium text-sm">
                      {filled} turnos generados {total > 0 && `· cobertura ${pct}%`}
                    </p>
                    {unfilled > 0 && (
                      <p className="text-xs text-muted-foreground">
                        {unfilled} ranuras sin cubrir — ver advertencias abajo
                      </p>
                    )}
                  </>
                );
              })()}
              {(() => {
                const stddev = computeEquityStdDev();
                if (!stddev) return null;
                const balanced = Number(stddev) < EQUITY_BALANCED_THRESHOLD_HOURS;
                return (
                  <p className="text-xs text-muted-foreground flex items-center gap-1">
                    {balanced && <Check className="h-3 w-3 text-emerald-600" />}
                    {balanced
                      ? "Carga equilibrada entre empleados"
                      : `Desviación de equidad: ${stddev}h entre empleados`}
                  </p>
                );
              })()}
            </div>

            {/* Stats per employee */}
            <div className="space-y-2">
              <Label>Distribución por empleado</Label>
              <div className="max-h-48 overflow-y-auto rounded border">
                <table className="w-full text-xs">
                  <thead className="bg-muted/50 sticky top-0">
                    <tr className="text-left">
                      <th className="px-2 py-1 font-medium">Empleado</th>
                      <th className="px-2 py-1 font-medium text-right">Turnos</th>
                      <th className="px-2 py-1 font-medium text-right">Horas</th>
                      <th className="px-2 py-1 font-medium text-right" title="Domingos">D</th>
                      <th className="px-2 py-1 font-medium text-right" title="Sábados">S</th>
                      <th className="px-2 py-1 font-medium text-right" title="Nocturnos">N</th>
                      <th className="px-2 py-1 font-medium text-right" title="Festivos">F</th>
                    </tr>
                  </thead>
                  <tbody>
                    {Object.entries(result.stats)
                      .filter(([, v]) => v.shifts > 0)
                      .sort((a, b) => b[1].hours - a[1].hours)
                      .map(([empId, stat]) => {
                        const emp = employees.find((e) => e.id === empId);
                        const b = perEmpBreakdown.get(empId) ?? {
                          D: 0,
                          S: 0,
                          N: 0,
                          F: 0,
                        };
                        return (
                          <tr key={empId} className="border-t">
                            <td className="px-2 py-1">
                              {emp
                                ? `${emp.first_name} ${emp.last_name}`
                                : empId}
                            </td>
                            <td className="px-2 py-1 text-right">{stat.shifts}</td>
                            <td className="px-2 py-1 text-right">
                              {Math.round(stat.hours)}h
                            </td>
                            <td className="px-2 py-1 text-right">{b.D}</td>
                            <td className="px-2 py-1 text-right">{b.S}</td>
                            <td className="px-2 py-1 text-right">{b.N}</td>
                            <td className="px-2 py-1 text-right">{b.F}</td>
                          </tr>
                        );
                      })}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Warnings */}
            {result.warnings.length > 0 && (
              <div className="space-y-2">
                <Label className="flex items-center gap-1 text-amber-600">
                  <AlertTriangle className="h-4 w-4" />
                  Advertencias ({result.warnings.length})
                </Label>

                {/* Resumen claro por empleado y gaps */}
                {(() => {
                  const totalAssigned = result.entries.length;
                  const totalExtras = result.entries.filter((e) => e.overtime_status === "pending").length;
                  const totalNoExtras = totalAssigned - totalExtras;
                  const gaps = result.warnings.filter(
                    (w) =>
                      w.kind === "coverage_gap" ||
                      w.kind === "no_safe_candidate" ||
                      w.kind === "holiday_hours_exceed_cap",
                  ).length;

                  // Mapa nombre por empleado
                  const employeeNameMap = new Map<string, string>(
                    employees.map((e) => [e.id, `${e.first_name} ${e.last_name}`]),
                  );

                  // Agrupar extras por empleado
                  const extrasByEmp = new Map<string, { name: string; reasons: Set<string> }>();
                  for (const w of result.warnings) {
                    if (w.kind === "overtime_assigned") {
                      const empName = employeeNameMap.get(w.employeeId) ?? "Empleado";
                      const entry = extrasByEmp.get(w.employeeId) ?? { name: empName, reasons: new Set<string>() };
                      for (const cap of w.caps) {
                        const label =
                          cap === "weekly_hours" ? "Horas semana"
                          : cap === "consecutive_days" ? "Días consecutivos"
                          : cap === "night_limit" ? "Turnos nocturnos"
                          : cap === "sundays_quarter" ? "Domingos del trimestre"
                          : "Festivos del trimestre";
                        entry.reasons.add(label);
                      }
                      extrasByEmp.set(w.employeeId, entry);
                    }
                  }

                  if (totalExtras === 0 && gaps === 0) return null;

                  return (
                    <div className="rounded-md border bg-muted/30 p-3 mb-1 space-y-2 text-sm">
                      <div className="flex flex-wrap items-center gap-4">
                        <span className="text-emerald-700">
                          <strong>{totalNoExtras}</strong> turnos sin extras
                        </span>
                        {totalExtras > 0 && (
                          <span className="text-amber-700">
                            <strong>{totalExtras}</strong> requieren aprobación de extras
                          </span>
                        )}
                        {gaps > 0 && (
                          <span className="text-red-700">
                            <strong>{gaps}</strong> sin cubrir
                          </span>
                        )}
                      </div>
                      {extrasByEmp.size > 0 && (
                        <div className="text-xs text-muted-foreground space-y-0.5">
                          {Array.from(extrasByEmp.values()).map((e) => (
                            <div key={e.name}>
                              · <strong className="text-foreground">{e.name}</strong> — {Array.from(e.reasons).join(", ")}
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  );
                })()}

                <div className="space-y-2">
                  {groupWarnings(result.warnings).filter((g) => g.kind !== "overtime_assigned").map((g) => {
                    const posNames = Array.from(g.affectedPositions)
                      .map((id) => positions.find((p) => p.id === id)?.name ?? id)
                      .join(", ");
                    if (g.kind === "coverage_gap") {
                      return (
                        <div key={g.kind} className="rounded border border-red-200 bg-red-50 p-3 text-xs">
                          <p className="font-medium text-red-800">
                            {g.count} {g.count === 1 ? "slot quedó sin cubrir" : "slots quedaron sin cubrir"} — todos los empleados elegibles estaban en cap inviolable.
                          </p>
                          {posNames && (
                            <p className="text-red-700 mt-1">
                              Posición afectada: <span className="font-medium">{posNames}</span>
                            </p>
                          )}
                        </div>
                      );
                    }
                    if (g.kind === "no_employees_in_position") {
                      return (
                        <div key={g.kind} className="rounded border border-amber-200 bg-amber-50 p-3 text-xs">
                          <p className="font-medium text-amber-800">
                            {g.count} ranuras sin cubrir — posición sin empleados asignados
                          </p>
                          <p className="text-amber-700 mt-1">
                            Posición afectada: <span className="font-medium">{posNames}</span>
                          </p>
                          <button
                            type="button"
                            onClick={() => navigateAndClose("/employees")}
                            className="mt-2 inline-flex items-center gap-1 text-amber-800 underline hover:text-amber-900"
                          >
                            Asignar empleados a esta posición <ArrowRight className="h-3 w-3" />
                          </button>
                        </div>
                      );
                    }
                    if (g.kind === "holiday_hours_exceed_cap") {
                      // Agrupar por (posición, horas de festivo, tope diario) para que
                      // cada posición muestre SUS propios números en vez de heredar los
                      // del primer warning global.
                      const byPosition = new Map<
                        string,
                        { positionId: string; holidayHours: number; maxDayCap: number; count: number }
                      >();
                      for (const w of result.warnings) {
                        if (w.kind !== "holiday_hours_exceed_cap") continue;
                        const key = `${w.positionId}|${w.holidayHours}|${w.maxDayCap}`;
                        const grp = byPosition.get(key) ?? {
                          positionId: w.positionId,
                          holidayHours: w.holidayHours,
                          maxDayCap: w.maxDayCap,
                          count: 0,
                        };
                        grp.count++;
                        byPosition.set(key, grp);
                      }
                      const groups = Array.from(byPosition.values()).sort((a, b) => b.count - a.count);
                      if (groups.length === 0) return null;
                      return (
                        <div key={g.kind} className="space-y-2">
                          {groups.map((grp) => {
                            const posName =
                              positions.find((p) => p.id === grp.positionId)?.name ?? grp.positionId;
                            return (
                              <div
                                key={`${grp.positionId}-${grp.holidayHours}-${grp.maxDayCap}`}
                                className="rounded border border-orange-200 bg-orange-50 p-3 text-xs"
                              >
                                <p className="font-medium text-orange-800">
                                  {grp.count} {grp.count === 1 ? "slot de festivo sin cubrir" : "slots de festivo sin cubrir"} — horario de festivo demasiado largo
                                </p>
                                <p className="text-orange-700 mt-1">
                                  El horario de festivo de <span className="font-medium">{posName}</span> ({grp.holidayHours}h) supera el tope diario del contrato ({grp.maxDayCap}h): nadie puede cubrirlo en festivos. Reducí el horario de festivo del turno.
                                </p>
                                <button
                                  type="button"
                                  onClick={() => navigateAndClose("/shifts")}
                                  className="mt-2 inline-flex items-center gap-1 text-orange-800 underline hover:text-orange-900"
                                >
                                  Editar turnos <ArrowRight className="h-3 w-3" />
                                </button>
                              </div>
                            );
                          })}
                        </div>
                      );
                    }
                    if (g.kind === "no_safe_candidate") {
                      return (
                        <div key={g.kind} className="rounded border border-amber-200 bg-amber-50 p-3 text-xs">
                          <p className="font-medium text-amber-800">
                            {g.count} ranuras sin cubrir — capacidad agotada
                          </p>
                          <p className="text-amber-700 mt-1">
                            Los empleados elegibles llegaron a su límite semanal, de descanso o de días consecutivos.
                          </p>
                          <div className="mt-2 flex gap-3">
                            <button
                              type="button"
                              onClick={() => navigateAndClose("/settings")}
                              className="inline-flex items-center gap-1 text-amber-800 underline hover:text-amber-900"
                            >
                              Revisar restricciones <ArrowRight className="h-3 w-3" />
                            </button>
                            <button
                              type="button"
                              onClick={() => navigateAndClose("/employees")}
                              className="inline-flex items-center gap-1 text-amber-800 underline hover:text-amber-900"
                            >
                              Sumar personal <ArrowRight className="h-3 w-3" />
                            </button>
                          </div>
                        </div>
                      );
                    }
                    if (g.kind === "no_templates_selected") {
                      return (
                        <div key={g.kind} className="rounded border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800">
                          No se seleccionaron plantillas de turno.
                        </div>
                      );
                    }
                    return (
                      <div key={g.kind} className="rounded border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800">
                        No se seleccionaron empleados.
                      </div>
                    );
                  })}
                </div>
              </div>
            )}
          </div>
            );
          })()
        )}

        <DialogFooter>
          {!result ? (
            <>
              <Button
                variant="outline"
                onClick={() => onOpenChange(false)}
              >
                Cancelar
              </Button>
              <Button
                onClick={handleGenerate}
                disabled={
                  generating ||
                  constraintsLoading ||
                  selTemplates.size === 0 ||
                  (!useDemand && selPositions.size === 0) ||
                  selEmployees.size === 0
                }
              >
                {generating && (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                )}
                Generar vista previa
              </Button>
            </>
          ) : (
            <>
              <Button variant="outline" onClick={() => setResult(null)}>
                Volver a configurar
              </Button>
              <Button
                onClick={handleApply}
                disabled={applying || result.entries.length === 0}
              >
                {applying && (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                )}
                Aplicar {result.entries.length} turnos
              </Button>
            </>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
