"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Loader2, Wand2, AlertTriangle } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { translateDbError } from "@/lib/utils";
import { toast } from "sonner";
import { generateSchedule } from "@/lib/schedule-generator";
import { MONTHS } from "@/lib/constants";
import { useSettings } from "@/hooks/use-settings";
import type {
  Profile,
  ProfileWithPositions,
  ShiftTemplate,
  Position,
  Schedule,
  ScheduleEntry,
  StaffingRequirement,
  AutoGenResult,
} from "@/lib/types";

interface AutoGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  schedule: Schedule;
  employees: Profile[];
  shiftTemplates: ShiftTemplate[];
  positions: Position[];
  existingEntries: ScheduleEntry[];
  month: number;
  year: number;
  onGenerated: () => void;
}

export function AutoGenerateDialog({
  open,
  onOpenChange,
  schedule,
  employees,
  shiftTemplates,
  positions,
  existingEntries,
  month,
  year,
  onGenerated,
}: AutoGenerateDialogProps) {
  const supabase = createClient();
  const { constraints, loading: constraintsLoading } = useSettings();
  const [generating, setGenerating] = useState(false);
  const [applying, setApplying] = useState(false);
  const [result, setResult] = useState<AutoGenResult | null>(null);

  // Selection state: all selected by default
  const [selTemplates, setSelTemplates] = useState<Set<string>>(
    new Set(shiftTemplates.map((t) => t.id))
  );
  const [selPositions, setSelPositions] = useState<Set<string>>(
    new Set(positions.map((p) => p.id))
  );
  const [selEmployees, setSelEmployees] = useState<Set<string>>(
    new Set(employees.map((e) => e.id))
  );

  // Demand mode
  const [useDemand, setUseDemand] = useState(false);
  const [staffingReqs, setStaffingReqs] = useState<StaffingRequirement[]>([]);
  const [hasStaffingConfig, setHasStaffingConfig] = useState(false);

  // Fetch staffing requirements on open
  useEffect(() => {
    if (!open) return;
    async function fetchStaffing() {
      const { data } = await supabase
        .from("staffing_requirements")
        .select("*")
        .eq("location_id", schedule.location_id);
      const reqs = (data ?? []) as StaffingRequirement[];
      setStaffingReqs(reqs);
      const hasConfig = reqs.length > 0;
      setHasStaffingConfig(hasConfig);
      setUseDemand(hasConfig);
    }
    fetchStaffing();
  }, [open, supabase, schedule.location_id]);

  // Reset when dialog opens
  function handleOpenChange(isOpen: boolean) {
    if (isOpen) {
      setResult(null);
      setSelTemplates(new Set(shiftTemplates.map((t) => t.id)));
      setSelPositions(new Set(positions.map((p) => p.id)));
      setSelEmployees(new Set(employees.map((e) => e.id)));
    }
    onOpenChange(isOpen);
  }

  function toggleSet(set: Set<string>, id: string): Set<string> {
    const next = new Set(set);
    if (next.has(id)) next.delete(id);
    else next.add(id);
    return next;
  }

  async function handleGenerate() {
    setGenerating(true);

    // Fetch approved time-off for selected employees
    const { data: timeOff } = await supabase
      .from("time_off_requests")
      .select("employee_id, start_date, end_date")
      .eq("status", "approved")
      .in("employee_id", Array.from(selEmployees));

    // Fetch employees with secondary positions
    const { data: secondaryData } = await supabase
      .from("employee_secondary_positions")
      .select("employee_id, position_id")
      .in("employee_id", Array.from(selEmployees));

    // Build ProfileWithPositions
    const secondaryMap = new Map<string, { employee_id: string; position_id: string; id: string; created_at: string }[]>();
    for (const sp of secondaryData ?? []) {
      if (!secondaryMap.has(sp.employee_id)) secondaryMap.set(sp.employee_id, []);
      secondaryMap.get(sp.employee_id)!.push({
        id: "",
        employee_id: sp.employee_id,
        position_id: sp.position_id,
        created_at: "",
      });
    }

    const employeesWithPositions: ProfileWithPositions[] = employees
      .filter((e) => selEmployees.has(e.id))
      .map((e) => ({
        ...e,
        secondary_positions: secondaryMap.get(e.id) ?? [],
      }));

    // When demand mode is on, gather position IDs from staffing requirements
    const positionIds = useDemand
      ? [...new Set(staffingReqs.map((r) => r.position_id))]
      : Array.from(selPositions);

    const genResult = generateSchedule(
      {
        scheduleId: schedule.id,
        locationId: schedule.location_id,
        month,
        year,
        shiftTemplateIds: Array.from(selTemplates),
        positionIds,
        excludeDates: [],
        employeeIds: Array.from(selEmployees),
        useDemandRequirements: useDemand,
      },
      employeesWithPositions,
      shiftTemplates,
      existingEntries,
      timeOff || [],
      constraints,
      staffingReqs
    );

    setResult(genResult);
    setGenerating(false);
  }

  async function handleApply() {
    if (!result || result.entries.length === 0) return;
    setApplying(true);

    const { error } = await supabase
      .from("schedule_entries")
      .insert(result.entries);

    if (error) {
      toast.error(translateDbError(error.message, "Error al insertar turnos"));
    } else {
      toast.success(`${result.entries.length} turnos generados correctamente`);
      onOpenChange(false);
      onGenerated();
    }
    setApplying(false);
  }

  // Compute equity metric (standard deviation of hours)
  function computeEquityStdDev(): string {
    if (!result) return "";
    const hourValues = Object.values(result.stats)
      .filter((v) => v.shifts > 0)
      .map((v) => v.hours);
    if (hourValues.length < 2) return "";
    const mean = hourValues.reduce((a, b) => a + b, 0) / hourValues.length;
    const variance = hourValues.reduce((sum, h) => sum + (h - mean) ** 2, 0) / hourValues.length;
    const stdDev = Math.sqrt(variance);
    return stdDev.toFixed(1);
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="max-w-lg max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Wand2 className="h-5 w-5" />
            Auto-generar horario
          </DialogTitle>
          <DialogDescription>
            Genera automaticamente turnos para {MONTHS[month]} {year}
          </DialogDescription>
        </DialogHeader>

        {!result ? (
          /* Configuration step */
          <div className="space-y-4 py-2">
            {/* Demand mode toggle */}
            {hasStaffingConfig && (
              <div className="flex items-center gap-2 rounded-md border p-3 bg-muted/50">
                <input
                  type="checkbox"
                  id="demand-mode"
                  checked={useDemand}
                  onChange={(e) => setUseDemand(e.target.checked)}
                  className="h-4 w-4 rounded"
                />
                <div>
                  <Label htmlFor="demand-mode" className="cursor-pointer text-sm font-medium">
                    Usar necesidades de personal
                  </Label>
                  <p className="text-xs text-muted-foreground">
                    Genera turnos basado en la demanda configurada por posicion, turno y dia
                  </p>
                </div>
              </div>
            )}

            {/* Templates */}
            <div className="space-y-2">
              <Label>Plantillas de turno</Label>
              <div className="flex flex-wrap gap-2">
                {shiftTemplates.map((t) => (
                  <button
                    key={t.id}
                    type="button"
                    onClick={() => setSelTemplates(toggleSet(selTemplates, t.id))}
                    className={`rounded-full px-3 py-1 text-xs font-medium border transition-colors ${
                      selTemplates.has(t.id)
                        ? "bg-primary text-primary-foreground border-primary"
                        : "bg-background text-muted-foreground border-border"
                    }`}
                  >
                    {t.name}
                  </button>
                ))}
              </div>
            </div>

            {/* Positions — hide when demand mode is on since positions come from requirements */}
            {!useDemand && (
              <div className="space-y-2">
                <Label>Posiciones</Label>
                <div className="flex flex-wrap gap-2">
                  {positions.map((p) => (
                    <button
                      key={p.id}
                      type="button"
                      onClick={() => setSelPositions(toggleSet(selPositions, p.id))}
                      className={`rounded-full px-3 py-1 text-xs font-medium border transition-colors ${
                        selPositions.has(p.id)
                          ? "border-transparent text-white"
                          : "bg-background text-muted-foreground border-border"
                      }`}
                      style={
                        selPositions.has(p.id)
                          ? { backgroundColor: p.color }
                          : undefined
                      }
                    >
                      {p.name}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* Employees */}
            <div className="space-y-2">
              <Label>
                Empleados ({selEmployees.size}/{employees.length})
              </Label>
              <div className="max-h-32 overflow-y-auto rounded border p-2 space-y-1">
                {employees.map((e) => (
                  <label
                    key={e.id}
                    className="flex items-center gap-2 text-sm cursor-pointer"
                  >
                    <input
                      type="checkbox"
                      checked={selEmployees.has(e.id)}
                      onChange={() =>
                        setSelEmployees(toggleSet(selEmployees, e.id))
                      }
                      className="rounded"
                    />
                    {e.first_name} {e.last_name}
                  </label>
                ))}
              </div>
            </div>

            {/* Constraints info */}
            {!constraintsLoading && (
              <div className="text-xs text-muted-foreground rounded border p-2">
                <span className="font-medium">Restricciones:</span>{" "}
                Max {constraints.maxHoursPerWeek}h/sem, {constraints.maxHoursPerDay}h/dia,{" "}
                {constraints.minRestHoursBetweenShifts}h descanso, {constraints.maxConsecutiveDays} dias consecutivos max
              </div>
            )}
          </div>
        ) : (
          /* Results step */
          <div className="space-y-4 py-2">
            <div className="rounded-md bg-muted p-3">
              <p className="font-medium text-sm">
                {result.entries.length} turnos generados
              </p>
              {computeEquityStdDev() && (
                <p className="text-xs text-muted-foreground mt-1">
                  Desviacion de equidad: {computeEquityStdDev()}h (menor = mas equitativo)
                </p>
              )}
            </div>

            {/* Stats per employee */}
            <div className="space-y-2">
              <Label>Distribucion por empleado</Label>
              <div className="max-h-40 overflow-y-auto rounded border p-2 space-y-1">
                {Object.entries(result.stats)
                  .filter(([, v]) => v.shifts > 0)
                  .sort((a, b) => b[1].hours - a[1].hours)
                  .map(([empId, stat]) => {
                    const emp = employees.find((e) => e.id === empId);
                    return (
                      <div
                        key={empId}
                        className="flex justify-between text-sm"
                      >
                        <span>
                          {emp
                            ? `${emp.first_name} ${emp.last_name}`
                            : empId}
                        </span>
                        <span className="text-muted-foreground">
                          {stat.shifts} turnos · {Math.round(stat.hours)}h
                        </span>
                      </div>
                    );
                  })}
              </div>
            </div>

            {/* Warnings */}
            {result.warnings.length > 0 && (
              <div className="space-y-2">
                <Label className="flex items-center gap-1 text-amber-600">
                  <AlertTriangle className="h-4 w-4" />
                  Advertencias ({result.warnings.length})
                </Label>
                <div className="max-h-24 overflow-y-auto rounded border border-amber-200 bg-amber-50 p-2 space-y-0.5">
                  {result.warnings.slice(0, 10).map((w, i) => (
                    <p key={i} className="text-xs text-amber-700">
                      {w}
                    </p>
                  ))}
                  {result.warnings.length > 10 && (
                    <p className="text-xs text-amber-600 font-medium">
                      ...y {result.warnings.length - 10} mas
                    </p>
                  )}
                </div>
              </div>
            )}
          </div>
        )}

        <DialogFooter>
          {!result ? (
            <>
              <Button
                variant="outline"
                onClick={() => onOpenChange(false)}
              >
                Cancelar
              </Button>
              <Button
                onClick={handleGenerate}
                disabled={
                  generating ||
                  constraintsLoading ||
                  selTemplates.size === 0 ||
                  (!useDemand && selPositions.size === 0) ||
                  selEmployees.size === 0
                }
              >
                {generating && (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                )}
                Generar vista previa
              </Button>
            </>
          ) : (
            <>
              <Button variant="outline" onClick={() => setResult(null)}>
                Volver a configurar
              </Button>
              <Button
                onClick={handleApply}
                disabled={applying || result.entries.length === 0}
              >
                {applying && (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                )}
                Aplicar {result.entries.length} turnos
              </Button>
            </>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
