"use client";

import { useEffect, useState, useCallback, useMemo } from "react";
import { createClient } from "@/lib/supabase/client";
import { useAuth } from "@/hooks/use-auth";
import { useEquityRollups } from "@/hooks/use-equity-rollups";
import { toast } from "sonner";
import { Loader2 } from "lucide-react";
import { getMonthDates, formatDateISO, buildEntryMap, translateDbError } from "@/lib/utils";
import { MONTHS } from "@/lib/constants";
import { ScheduleToolbar } from "@/components/schedule/schedule-toolbar";
import { ScheduleCalendarGrid, NO_DEPARTMENT_KEY, NO_DEPARTMENT_LABEL } from "@/components/schedule/schedule-calendar-grid";
import { DepartmentFilter, type DepartmentOption } from "@/components/schedule/department-filter";
import { ShiftAssignDialog } from "@/components/schedule/shift-assign-dialog";
import { EmployeeScheduleView } from "@/components/schedule/employee-schedule-view";
import { AutoGenerateDialog } from "@/components/schedule/auto-generate-dialog";
import { ExportDropdown } from "@/components/schedule/export-dropdown";
import { ScheduleHealthBanner } from "@/components/schedule/schedule-health-banner";
import { ScheduleHealthPanel } from "@/components/schedule/schedule-health-panel";
import { computeHealth } from "@/lib/schedule-health";
import { isHoliday, effectiveShiftHours, resolveSavedShiftBreakAndNight } from "@/lib/equity-helpers";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import type {
  Location,
  Profile,
  Position,
  ShiftTemplate,
  Schedule,
  ScheduleEntry,
  ScheduleStatus,
  ContractType,
  HolidayDate,
  ScoringWeights,
  LaborConstraints,
  StaffingRequirement,
  RestRule,
  EmployeeRestRule,
  EmployeeSecondaryPosition,
} from "@/lib/types";
import { canManage as canManageFn, canAdmin } from "@/lib/auth/can-manage";

export default function SchedulePage() {
  const { user, profile, effectiveOrgId, loading: authLoading } = useAuth();
  const supabase = createClient();

  // Core state
  const [locations, setLocations] = useState<Location[]>([]);
  const [selectedLocationId, setSelectedLocationId] = useState("");
  const [month, setMonth] = useState(new Date().getMonth());
  const [year, setYear] = useState(new Date().getFullYear());

  // Schedule data
  const [schedule, setSchedule] = useState<Schedule | null>(null);
  const [entries, setEntries] = useState<ScheduleEntry[]>([]);
  const [employees, setEmployees] = useState<Profile[]>([]);
  const [positions, setPositions] = useState<Position[]>([]);
  const [shiftTemplates, setShiftTemplates] = useState<ShiftTemplate[]>([]);

  // Equity model data sources
  const [contractTypes, setContractTypes] = useState<ContractType[]>([]);
  const [holidays, setHolidays] = useState<HolidayDate[]>([]);
  const rollups = useEquityRollups(year - 1);
  const [scoringWeights, setScoringWeights] = useState<ScoringWeights | null>(null);

  // Health model data sources
  const [staffingRequirements, setStaffingRequirements] = useState<StaffingRequirement[]>([]);
  const [constraints, setConstraints] = useState<LaborConstraints | null>(null);
  const [restRules, setRestRules] = useState<RestRule[]>([]);
  const [employeeRestRules, setEmployeeRestRules] = useState<EmployeeRestRule[]>([]);

  // UI state
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  // Dialog state
  const [dialogOpen, setDialogOpen] = useState(false);
  const [dialogMode, setDialogMode] = useState<"employee" | "gap">("employee");
  const [dialogEmployeeId, setDialogEmployeeId] = useState("");
  const [dialogDate, setDialogDate] = useState("");
  const [dialogEntry, setDialogEntry] = useState<ScheduleEntry | null>(null);
  const [dialogGapPositionId, setDialogGapPositionId] = useState<string>("");
  const [dialogGapShiftTemplateId, setDialogGapShiftTemplateId] = useState<string>("");

  // Secondary positions (for filtering eligible employees when covering a gap)
  const [secondaryPositions, setSecondaryPositions] = useState<EmployeeSecondaryPosition[]>([]);

  // Department filter (persisted per location in localStorage)
  const [selectedDepartmentIds, setSelectedDepartmentIds] = useState<Set<string> | null>(null);

  // Auto-generate dialog state
  const [autoGenOpen, setAutoGenOpen] = useState(false);

  // Clear-draft confirmation dialog state
  const [clearDraftOpen, setClearDraftOpen] = useState(false);

  const isAdmin = canAdmin(profile?.role);
  const isManager = profile?.role === "manager";
  const isEmployee = profile?.role === "employee";
  const canManage = canManageFn(profile?.role);

  // Fetch locations on mount
  useEffect(() => {
    if (authLoading) return;

    async function fetchLocations() {
      const { data } = await supabase
        .from("locations")
        .select("*")
        .order("name");
      if (data && data.length > 0) {
        setLocations(data);
        // Default to user's location or first
        const defaultLoc = profile?.location_id || data[0].id;
        setSelectedLocationId(defaultLoc);
      }
      setLoading(false);
    }

    fetchLocations();
  }, [authLoading, profile?.location_id]);

  // Fetch schedule + employees + entries when location/month/year change.
  // Pass `{ silent: true }` after a save/delete so the grid doesn't unmount
  // (which would reset horizontal scroll).
  const fetchScheduleData = useCallback(async (opts?: { silent?: boolean }) => {
    if (!selectedLocationId) return;
    if (!opts?.silent) setLoading(true);

    try {
      // Queries 1-5 are independent — run in parallel
      const [scheduleResult, empResult, posResult, shiftResult, secondaryResult] = await Promise.all([
        supabase
          .from("schedules")
          .select("*")
          .eq("location_id", selectedLocationId)
          .eq("month", month + 1)
          .eq("year", year)
          .maybeSingle(),
        supabase
          .from("profiles")
          .select("*, position:positions(*, department:departments(id, name)), location:locations(*)")
          .eq("location_id", selectedLocationId)
          .eq("is_active", true)
          .order("last_name"),
        supabase
          .from("positions")
          .select("*, department:departments!inner(id, name, location_id)")
          .eq("department.location_id", selectedLocationId)
          .order("name"),
        supabase
          .from("shift_templates")
          .select("*")
          .eq("location_id", selectedLocationId)
          .order("name"),
        supabase
          .from("employee_secondary_positions")
          .select("*"),
      ]);

      const scheduleData = scheduleResult.data;
      setSchedule(scheduleData);
      setEmployees((empResult.data as Profile[]) || []);
      setPositions((posResult.data as Position[]) || []);
      setShiftTemplates(shiftResult.data || []);
      setSecondaryPositions((secondaryResult.data as EmployeeSecondaryPosition[]) || []);

      // Query 6 depends on schedule existing
      if (scheduleData) {
        const { data: entryData } = await supabase
          .from("schedule_entries")
          .select("*, employee:profiles!schedule_entries_employee_id_fkey(id, first_name, last_name), position:positions(*), shift_template:shift_templates(*)")
          .eq("schedule_id", scheduleData.id)
          .neq("overtime_status", "rejected");
        setEntries((entryData as ScheduleEntry[]) || []);
      } else {
        setEntries([]);
      }
    } catch (err) {
      toast.error("Error al cargar datos del horario");
    }

    if (!opts?.silent) setLoading(false);
  }, [selectedLocationId, month, year, supabase]);

  useEffect(() => {
    if (selectedLocationId) {
      fetchScheduleData();
    }
  }, [fetchScheduleData, selectedLocationId]);

  // Fetch equity model data (contract types, holidays, weights). Rollups
  // are loaded and kept in sync via useEquityRollups above.
  useEffect(() => {
    if (!selectedLocationId) return;
    (async () => {
      const [{ data: cts }, { data: hols }, { data: weights }, { data: staffing }, { data: laborConstraintsRow }, { data: restRulesData }, { data: empRestRulesData }] = await Promise.all([
        supabase.from("contract_types").select("*"),
        supabase
          .from("holidays")
          .select("*")
          .or(`location_id.is.null,location_id.eq.${selectedLocationId}`),
        supabase
          .from("app_settings")
          .select("value")
          .eq("key", "scoring_weights")
          .maybeSingle(),
        supabase
          .from("staffing_requirements")
          .select("*")
          .eq("location_id", selectedLocationId),
        supabase
          .from("app_settings")
          .select("value")
          .eq("key", "labor_constraints")
          .maybeSingle(),
        supabase.from("contract_rest_rules").select("*"),
        supabase.from("employee_rest_rules").select("*"),
      ]);
      setContractTypes((cts ?? []) as ContractType[]);
      setHolidays((hols ?? []) as HolidayDate[]);
      setScoringWeights((weights?.value as ScoringWeights | null) ?? null);
      setStaffingRequirements((staffing ?? []) as StaffingRequirement[]);
      setConstraints(
        (laborConstraintsRow?.value as LaborConstraints | null) ?? {
          maxHoursPerWeek: 40,
          maxHoursPerDay: 10,
          minRestHoursBetweenShifts: 12,
          maxConsecutiveDays: 6,
        },
      );
      setRestRules((restRulesData ?? []) as unknown as RestRule[]);
      setEmployeeRestRules((empRestRulesData ?? []) as unknown as EmployeeRestRule[]);
    })();
  }, [supabase, selectedLocationId]);

  // Navigation
  function handlePrevMonth() {
    if (month === 0) {
      setMonth(11);
      setYear(year - 1);
    } else {
      setMonth(month - 1);
    }
  }

  function handleNextMonth() {
    if (month === 11) {
      setMonth(0);
      setYear(year + 1);
    } else {
      setMonth(month + 1);
    }
  }

  // Schedule lifecycle
  async function handleCreateDraft() {
    if (!selectedLocationId || !user) return;
    setSaving(true);

    const { data, error } = await supabase
      .from("schedules")
      .insert({
        location_id: selectedLocationId,
        month: month + 1,
        year: year,
        status: "draft" as const,
        created_by: user.id,
        organization_id: effectiveOrgId ?? "",
      })
      .select()
      .single();

    if (error) {
      toast.error(translateDbError(error.message, "Error al crear borrador"));
    } else {
      setSchedule(data);
      toast.success("Borrador creado para " + MONTHS[month] + " " + year);
    }
    setSaving(false);
  }

  async function handlePublish() {
    if (!schedule) return;
    setSaving(true);

    const { error } = await supabase
      .from("schedules")
      .update({ status: "published" as const, published_at: new Date().toISOString() })
      .eq("id", schedule.id);

    if (error) {
      toast.error(translateDbError(error.message, "Error al publicar el horario"));
    } else {
      setSchedule({ ...schedule, status: "published" });
      toast.success("Horario publicado correctamente");
    }
    setSaving(false);
  }

  async function handleArchive() {
    if (!schedule) return;
    setSaving(true);

    const { error } = await supabase
      .from("schedules")
      .update({ status: "archived" as const })
      .eq("id", schedule.id);

    if (error) {
      toast.error(translateDbError(error.message, "Error al archivar el horario"));
    } else {
      setSchedule({ ...schedule, status: "archived" });
      toast.success("Horario archivado");
    }
    setSaving(false);
  }

  // Cell click handler
  function handleCellClick(
    employeeId: string,
    date: string,
    entry: ScheduleEntry | null
  ) {
    if (!canManage || !schedule || schedule.status !== "draft") return;
    setDialogMode("employee");
    setDialogEmployeeId(employeeId);
    setDialogDate(date);
    setDialogEntry(entry);
    setDialogGapPositionId("");
    setDialogGapShiftTemplateId("");
    setDialogOpen(true);
  }

  // Gap click handler — opens dialog pre-filled with position + shift template
  // and an employee picker filtered to those who can cover the position
  function handleGapClick(positionId: string, date: string, shiftTemplateId: string) {
    if (!canManage || !schedule || schedule.status !== "draft") return;
    setDialogMode("gap");
    setDialogEmployeeId("");
    setDialogDate(date);
    setDialogEntry(null);
    setDialogGapPositionId(positionId);
    setDialogGapShiftTemplateId(shiftTemplateId);
    setDialogOpen(true);
  }

  // Save entry
  async function handleSaveEntry(data: {
    employee_id?: string;
    position_id: string;
    start_time: string;
    end_time: string;
    shift_template_id: string | null;
    notes: string;
  }) {
    if (!schedule) return;
    setSaving(true);

    // Carácter nocturno y descanso EFECTIVOS del turno que se guarda: solo se
    // heredan de la plantilla si las horas guardadas COINCIDEN con las efectivas de
    // la plantilla (consistente con el motor vía effectiveShiftHours). Si el usuario
    // editó las horas (p.ej. las acortó), el break/carácter de la plantilla ya no
    // corresponde al span real: se derivan de las horas realmente persistidas y el
    // break se pone en 0 (paga bruto, sin subpago). Aplica a insert y update.
    const tpl = shiftTemplates.find((t) => t.id === data.shift_template_id);
    const tplEffective = tpl ? effectiveShiftHours(tpl, dialogIsHolidayDate) : null;
    const { isNight, breakMinutes } = resolveSavedShiftBreakAndNight(
      tplEffective,
      data.start_time,
      data.end_time,
    );

    if (dialogEntry) {
      // Update existing
      const { error } = await supabase
        .from("schedule_entries")
        .update({
          position_id: data.position_id,
          start_time: data.start_time,
          end_time: data.end_time,
          shift_template_id: data.shift_template_id,
          notes: data.notes || null,
          is_night: isNight,
          break_minutes: breakMinutes,
        })
        .eq("id", dialogEntry.id);

      if (error) {
        toast.error(translateDbError(error.message, "Error al actualizar el turno"));
      } else {
        toast.success("Turno actualizado");
        setDialogOpen(false);
        fetchScheduleData({ silent: true });
      }
    } else {
      // Create new — gap mode passes its own employee_id, employee mode uses dialogEmployeeId
      const employeeId = data.employee_id ?? dialogEmployeeId;
      const { error } = await supabase.from("schedule_entries").insert({
        schedule_id: schedule.id,
        employee_id: employeeId,
        date: dialogDate,
        position_id: data.position_id,
        start_time: data.start_time,
        end_time: data.end_time,
        shift_template_id: data.shift_template_id,
        notes: data.notes || null,
        is_night: isNight,
        break_minutes: breakMinutes,
        organization_id: effectiveOrgId ?? "",
      });

      if (error) {
        toast.error(translateDbError(error.message, "Error al crear el turno"));
      } else {
        toast.success("Turno asignado");
        setDialogOpen(false);
        fetchScheduleData({ silent: true });
      }
    }

    setSaving(false);
  }

  // Delete entry
  async function handleDeleteEntry() {
    if (!dialogEntry) return;
    setSaving(true);

    const { error } = await supabase
      .from("schedule_entries")
      .delete()
      .eq("id", dialogEntry.id);

    if (error) {
      toast.error(translateDbError(error.message, "Error al eliminar el turno"));
    } else {
      toast.success("Turno eliminado");
      setDialogOpen(false);
      fetchScheduleData({ silent: true });
    }

    setSaving(false);
  }

  // Clear all entries from the current draft (keeps the schedule, removes the entries)
  async function handleClearDraftConfirm() {
    if (!schedule || schedule.status !== "draft") return;
    setSaving(true);

    const { error } = await supabase
      .from("schedule_entries")
      .delete()
      .eq("schedule_id", schedule.id);

    if (error) {
      toast.error(translateDbError(error.message, "Error al limpiar el borrador"));
    } else {
      toast.success("Borrador limpiado");
      setClearDraftOpen(false);
      fetchScheduleData({ silent: true });
    }

    setSaving(false);
  }

  // Department options for the filter (derived from positions in this location)
  const departmentOptions = useMemo<DepartmentOption[]>(() => {
    const map = new Map<string, string>();
    for (const p of positions) {
      const dep = p.department;
      const key = dep?.id ?? NO_DEPARTMENT_KEY;
      const label = dep?.name ?? NO_DEPARTMENT_LABEL;
      if (!map.has(key)) map.set(key, label);
    }
    return Array.from(map.entries())
      .map(([key, label]) => ({ key, label }))
      .sort((a, b) => {
        if (a.key === NO_DEPARTMENT_KEY) return 1;
        if (b.key === NO_DEPARTMENT_KEY) return -1;
        return a.label.localeCompare(b.label, "es");
      });
  }, [positions]);

  // Load/initialize department filter when location changes
  useEffect(() => {
    if (!selectedLocationId || departmentOptions.length === 0) return;
    const storageKey = `schedule.deptFilter.${selectedLocationId}`;
    let initial: Set<string> | null = null;
    try {
      const saved = window.localStorage.getItem(storageKey);
      if (saved) {
        const arr = JSON.parse(saved) as string[];
        // Drop ids that no longer exist; default to all if result empty
        const filtered = arr.filter((k) => departmentOptions.some((d) => d.key === k));
        if (filtered.length > 0) initial = new Set(filtered);
      }
    } catch {
      // ignore corrupted storage
    }
    setSelectedDepartmentIds(initial ?? new Set(departmentOptions.map((d) => d.key)));
  }, [selectedLocationId, departmentOptions]);

  function handleDepartmentFilterChange(next: Set<string>) {
    setSelectedDepartmentIds(next);
    if (selectedLocationId) {
      try {
        window.localStorage.setItem(
          `schedule.deptFilter.${selectedLocationId}`,
          JSON.stringify(Array.from(next)),
        );
      } catch {
        // ignore quota errors
      }
    }
  }

  // Overtime approve/reject — update local state to preserve scroll
  async function handleApproveOvertime(entryId: string) {
    const reviewedAt = new Date().toISOString();
    const { error } = await supabase
      .from("schedule_entries")
      .update({
        overtime_status: "approved" as const,
        overtime_reviewed_by: user?.id ?? null,
        overtime_reviewed_at: reviewedAt,
      })
      .eq("id", entryId);

    if (error) {
      toast.error(translateDbError(error.message, "Error al aprobar"));
      return;
    }
    toast.success("Hora extra aprobada");
    setEntries((prev) =>
      prev.map((e) =>
        e.id === entryId
          ? {
              ...e,
              overtime_status: "approved",
              overtime_reviewed_by: user?.id ?? null,
              overtime_reviewed_at: reviewedAt,
            }
          : e,
      ),
    );
  }

  async function handleRejectOvertime(entryId: string) {
    const reviewedAt = new Date().toISOString();
    const { error } = await supabase
      .from("schedule_entries")
      .update({
        overtime_status: "rejected" as const,
        overtime_reviewed_by: user?.id ?? null,
        overtime_reviewed_at: reviewedAt,
      })
      .eq("id", entryId);

    if (error) {
      toast.error(translateDbError(error.message, "Error al rechazar"));
      return;
    }
    toast.success("Hora extra rechazada");
    // Rejected entries are filtered out of the grid — remove locally
    setEntries((prev) => prev.filter((e) => e.id !== entryId));
  }

  // Compute schedule health summary
  const health = useMemo(() => {
    if (!selectedLocationId || !constraints) return null;
    if (entries.length === 0 && staffingRequirements.length === 0) return null;
    return computeHealth(
      entries,
      employees,
      staffingRequirements,
      constraints,
      selectedLocationId,
      year,
      month,
      restRules,
      contractTypes,
      employeeRestRules,
      holidays,
    );
  }, [entries, employees, staffingRequirements, constraints, selectedLocationId, year, month, restRules, contractTypes, employeeRestRules, holidays]);

  // Build entry map for grid
  const entryMap = buildEntryMap(entries);
  const dates = getMonthDates(year, month);

  // Find employee name for dialog (employee mode)
  const dialogEmployee = employees.find((e) => e.id === dialogEmployeeId);
  const dialogEmployeeName = dialogEmployee
    ? `${dialogEmployee.first_name} ${dialogEmployee.last_name}`
    : "";

  // Eligible employees for gap mode: primaries + those listing the gap position as secondary
  const eligibleGapEmployees = useMemo(() => {
    if (dialogMode !== "gap" || !dialogGapPositionId) return [];
    const secondaryEmpIds = new Set(
      secondaryPositions
        .filter((sp) => sp.position_id === dialogGapPositionId)
        .map((sp) => sp.employee_id),
    );
    return employees.filter(
      (e) =>
        e.position?.id === dialogGapPositionId || secondaryEmpIds.has(e.id),
    );
  }, [dialogMode, dialogGapPositionId, employees, secondaryPositions]);
  const dialogDateLabel = dialogDate
    ? new Date(dialogDate + "T00:00:00").toLocaleDateString("es-ES", {
        weekday: "long",
        day: "numeric",
        month: "long",
      })
    : "";
  // ¿La fecha de la celda/slot seleccionado es festivo? Deriva del ISO real
  // (dialogDate), no del dateLabel formateado. Decide el pre-llenado de horas
  // de festivo al elegir una plantilla en el diálogo de asignación.
  const dialogIsHolidayDate = dialogDate
    ? isHoliday(dialogDate, selectedLocationId, holidays)
    : false;

  // Loading state
  if (authLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  // Employee view: show only published schedules with their entries
  if (isEmployee) {
    const myEntries = entries.filter(
      (e) => e.employee_id === user?.id
    );

    return (
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold">Mis horarios</h1>
          <p className="text-muted-foreground">
            Tu calendario de turnos publicados
          </p>
        </div>

        {/* Location + month nav for employees too */}
        <ScheduleToolbar
          locations={locations}
          selectedLocationId={selectedLocationId}
          onLocationChange={setSelectedLocationId}
          month={month}
          year={year}
          onPrevMonth={handlePrevMonth}
          onNextMonth={handleNextMonth}
          scheduleStatus={schedule?.status || null}
          onCreateDraft={() => {}}
          onPublish={() => {}}
          onArchive={() => {}}
          isAdmin={false}
          isManager={false}
          saving={false}
        />

        {schedule?.status === "published" || schedule?.status === "archived" ? (
          <EmployeeScheduleView
            entries={myEntries}
            month={month}
            year={year}
            loading={loading}
          />
        ) : (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <p className="text-muted-foreground">
              No hay horario publicado para {MONTHS[month]} {year}.
            </p>
          </div>
        )}
      </div>
    );
  }

  // Admin / Manager view
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Horarios</h1>
        <p className="text-muted-foreground">
          Gestiona los horarios mensuales por sede
        </p>
      </div>

      <ScheduleToolbar
        locations={locations}
        selectedLocationId={selectedLocationId}
        onLocationChange={setSelectedLocationId}
        month={month}
        year={year}
        onPrevMonth={handlePrevMonth}
        onNextMonth={handleNextMonth}
        scheduleStatus={schedule?.status || null}
        onCreateDraft={handleCreateDraft}
        onPublish={handlePublish}
        onArchive={handleArchive}
        onAutoGenerate={() => setAutoGenOpen(true)}
        onClearDraft={entries.length > 0 ? () => setClearDraftOpen(true) : undefined}
        isAdmin={isAdmin}
        isManager={isManager}
        saving={saving}
      />

      {loading ? (
        <div className="flex items-center justify-center py-12">
          <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
        </div>
      ) : !schedule ? (
        <div className="flex flex-col items-center justify-center py-16 text-center rounded-md border bg-card">
          <p className="text-muted-foreground mb-2">
            No hay horario para {MONTHS[month]} {year}.
          </p>
          {canManage && selectedLocationId && (
            <p className="text-sm text-muted-foreground">
              Crea un borrador para comenzar a asignar turnos.
            </p>
          )}
        </div>
      ) : (
        <>
          {/* Export button when schedule has entries */}
          {entries.length > 0 && (
            <div className="flex justify-end">
              <ExportDropdown
                entries={entries}
                employees={employees}
                month={month}
                year={year}
                locationName={locations.find((l) => l.id === selectedLocationId)?.name || ""}
              />
            </div>
          )}

          {/* Schedule health */}
          {health && <ScheduleHealthBanner health={health} />}
          {health && (
            <ScheduleHealthPanel
              health={health}
              shiftTemplatesById={Object.fromEntries(shiftTemplates.map((s) => [s.id, { name: s.name }]))}
              positionsById={Object.fromEntries(positions.map((p) => [p.id, { name: p.name }]))}
            />
          )}

          {departmentOptions.length > 1 && selectedDepartmentIds && (
            <DepartmentFilter
              departments={departmentOptions}
              selectedIds={selectedDepartmentIds}
              onChange={handleDepartmentFilterChange}
            />
          )}

          <ScheduleCalendarGrid
            dates={dates}
            employees={employees}
            entryMap={entryMap}
            canEdit={canManage && schedule.status === "draft"}
            onCellClick={handleCellClick}
            onGapClick={handleGapClick}
            onApproveOvertime={canManage ? handleApproveOvertime : undefined}
            onRejectOvertime={canManage ? handleRejectOvertime : undefined}
            selectedDepartmentIds={selectedDepartmentIds ?? undefined}
            gaps={health?.gapsByDay ?? []}
            positionsById={Object.fromEntries(
              positions.map((p) => [
                p.id,
                {
                  name: p.name,
                  department: p.department
                    ? { id: p.department.id, name: p.department.name }
                    : null,
                },
              ])
            )}
            shiftTemplatesById={Object.fromEntries(
              shiftTemplates.map((s) => [
                s.id,
                { name: s.name, start_time: s.start_time, end_time: s.end_time },
              ])
            )}
          />
        </>
      )}

      {/* Auto-generate dialog */}
      {schedule && (
        <AutoGenerateDialog
          open={autoGenOpen}
          onOpenChange={setAutoGenOpen}
          schedule={schedule}
          employees={employees}
          shiftTemplates={shiftTemplates}
          positions={positions}
          existingEntries={entries}
          month={month}
          year={year}
          locationName={locations.find((l) => l.id === selectedLocationId)?.name ?? ""}
          contractTypes={contractTypes}
          holidays={holidays}
          rollups={rollups}
          scoringWeights={scoringWeights}
          onGenerated={fetchScheduleData}
        />
      )}

      {/* Assign dialog */}
      <ShiftAssignDialog
        open={dialogOpen}
        onOpenChange={setDialogOpen}
        mode={dialogMode}
        entry={dialogEntry}
        employeeName={dialogEmployeeName}
        eligibleEmployees={eligibleGapEmployees}
        initialPositionId={dialogGapPositionId || undefined}
        initialShiftTemplateId={dialogGapShiftTemplateId || undefined}
        dateLabel={dialogDateLabel}
        isHolidayDate={dialogIsHolidayDate}
        positions={positions}
        shiftTemplates={shiftTemplates}
        saving={saving}
        onSave={handleSaveEntry}
        onDelete={handleDeleteEntry}
      />

      {/* Clear-draft confirmation */}
      <AlertDialog open={clearDraftOpen} onOpenChange={setClearDraftOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Limpiar borrador</AlertDialogTitle>
            <AlertDialogDescription>
              Se eliminarán los {entries.length} turnos asignados de este borrador.
              El borrador se mantiene vacío para que vuelvas a auto-generar o asignar
              manualmente. Esta acción no se puede deshacer.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={saving}>Cancelar</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleClearDraftConfirm}
              disabled={saving}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              {saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
              Limpiar
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
