"use client";

import { useEffect, useState, useCallback } from "react";
import { createClient } from "@/lib/supabase/client";
import { useAuth } from "@/hooks/use-auth";
import { toast } from "sonner";
import { Loader2 } from "lucide-react";
import { getMonthDates, formatDateISO, buildEntryMap, translateDbError } from "@/lib/utils";
import { MONTHS } from "@/lib/constants";
import { ScheduleToolbar } from "@/components/schedule/schedule-toolbar";
import { ScheduleCalendarGrid } from "@/components/schedule/schedule-calendar-grid";
import { ShiftAssignDialog } from "@/components/schedule/shift-assign-dialog";
import { EmployeeScheduleView } from "@/components/schedule/employee-schedule-view";
import { AutoGenerateDialog } from "@/components/schedule/auto-generate-dialog";
import { ExportDropdown } from "@/components/schedule/export-dropdown";
import type {
  Location,
  Profile,
  Position,
  ShiftTemplate,
  Schedule,
  ScheduleEntry,
  ScheduleStatus,
} from "@/lib/types";

export default function SchedulePage() {
  const { user, profile, loading: authLoading } = useAuth();
  const supabase = createClient();

  // Core state
  const [locations, setLocations] = useState<Location[]>([]);
  const [selectedLocationId, setSelectedLocationId] = useState("");
  const [month, setMonth] = useState(new Date().getMonth());
  const [year, setYear] = useState(new Date().getFullYear());

  // Schedule data
  const [schedule, setSchedule] = useState<Schedule | null>(null);
  const [entries, setEntries] = useState<ScheduleEntry[]>([]);
  const [employees, setEmployees] = useState<Profile[]>([]);
  const [positions, setPositions] = useState<Position[]>([]);
  const [shiftTemplates, setShiftTemplates] = useState<ShiftTemplate[]>([]);

  // UI state
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  // Dialog state
  const [dialogOpen, setDialogOpen] = useState(false);
  const [dialogEmployeeId, setDialogEmployeeId] = useState("");
  const [dialogDate, setDialogDate] = useState("");
  const [dialogEntry, setDialogEntry] = useState<ScheduleEntry | null>(null);

  // Auto-generate dialog state
  const [autoGenOpen, setAutoGenOpen] = useState(false);

  const isAdmin = profile?.role === "admin";
  const isManager = profile?.role === "manager";
  const isEmployee = profile?.role === "employee";
  const canManage = isAdmin || isManager;

  // Fetch locations on mount
  useEffect(() => {
    if (authLoading) return;

    async function fetchLocations() {
      const { data } = await supabase
        .from("locations")
        .select("*")
        .order("name");
      if (data && data.length > 0) {
        setLocations(data);
        // Default to user's location or first
        const defaultLoc = profile?.location_id || data[0].id;
        setSelectedLocationId(defaultLoc);
      }
      setLoading(false);
    }

    fetchLocations();
  }, [authLoading, profile?.location_id]);

  // Fetch schedule + employees + entries when location/month/year change
  const fetchScheduleData = useCallback(async () => {
    if (!selectedLocationId) return;
    setLoading(true);

    try {
      // Queries 1-4 are independent — run in parallel
      const [scheduleResult, empResult, posResult, shiftResult] = await Promise.all([
        supabase
          .from("schedules")
          .select("*")
          .eq("location_id", selectedLocationId)
          .eq("month", month + 1)
          .eq("year", year)
          .maybeSingle(),
        supabase
          .from("profiles")
          .select("*, position:positions(*), location:locations(*)")
          .eq("location_id", selectedLocationId)
          .eq("is_active", true)
          .order("last_name"),
        supabase
          .from("positions")
          .select("*, department:departments!inner(name, location_id)")
          .eq("department.location_id", selectedLocationId)
          .order("name"),
        supabase
          .from("shift_templates")
          .select("*")
          .eq("location_id", selectedLocationId)
          .order("name"),
      ]);

      const scheduleData = scheduleResult.data;
      setSchedule(scheduleData);
      setEmployees((empResult.data as Profile[]) || []);
      setPositions((posResult.data as Position[]) || []);
      setShiftTemplates(shiftResult.data || []);

      // Query 5 depends on schedule existing
      if (scheduleData) {
        const { data: entryData } = await supabase
          .from("schedule_entries")
          .select("*, employee:profiles(id, first_name, last_name), position:positions(*), shift_template:shift_templates(*)")
          .eq("schedule_id", scheduleData.id);
        setEntries((entryData as ScheduleEntry[]) || []);
      } else {
        setEntries([]);
      }
    } catch (err) {
      toast.error("Error al cargar datos del horario");
    }

    setLoading(false);
  }, [selectedLocationId, month, year, supabase]);

  useEffect(() => {
    if (selectedLocationId) {
      fetchScheduleData();
    }
  }, [fetchScheduleData, selectedLocationId]);

  // Navigation
  function handlePrevMonth() {
    if (month === 0) {
      setMonth(11);
      setYear(year - 1);
    } else {
      setMonth(month - 1);
    }
  }

  function handleNextMonth() {
    if (month === 11) {
      setMonth(0);
      setYear(year + 1);
    } else {
      setMonth(month + 1);
    }
  }

  // Schedule lifecycle
  async function handleCreateDraft() {
    if (!selectedLocationId || !user) return;
    setSaving(true);

    const { data, error } = await supabase
      .from("schedules")
      .insert({
        location_id: selectedLocationId,
        month: month + 1,
        year: year,
        status: "draft" as const,
        created_by: user.id,
      })
      .select()
      .single();

    if (error) {
      toast.error(translateDbError(error.message, "Error al crear borrador"));
    } else {
      setSchedule(data);
      toast.success("Borrador creado para " + MONTHS[month] + " " + year);
    }
    setSaving(false);
  }

  async function handlePublish() {
    if (!schedule) return;
    setSaving(true);

    const { error } = await supabase
      .from("schedules")
      .update({ status: "published" as const, published_at: new Date().toISOString() })
      .eq("id", schedule.id);

    if (error) {
      toast.error(translateDbError(error.message, "Error al publicar el horario"));
    } else {
      setSchedule({ ...schedule, status: "published" });
      toast.success("Horario publicado correctamente");
    }
    setSaving(false);
  }

  async function handleArchive() {
    if (!schedule) return;
    setSaving(true);

    const { error } = await supabase
      .from("schedules")
      .update({ status: "archived" as const })
      .eq("id", schedule.id);

    if (error) {
      toast.error(translateDbError(error.message, "Error al archivar el horario"));
    } else {
      setSchedule({ ...schedule, status: "archived" });
      toast.success("Horario archivado");
    }
    setSaving(false);
  }

  // Cell click handler
  function handleCellClick(
    employeeId: string,
    date: string,
    entry: ScheduleEntry | null
  ) {
    if (!canManage || !schedule || schedule.status !== "draft") return;
    setDialogEmployeeId(employeeId);
    setDialogDate(date);
    setDialogEntry(entry);
    setDialogOpen(true);
  }

  // Save entry
  async function handleSaveEntry(data: {
    position_id: string;
    start_time: string;
    end_time: string;
    shift_template_id: string | null;
    notes: string;
  }) {
    if (!schedule) return;
    setSaving(true);

    if (dialogEntry) {
      // Update existing
      const { error } = await supabase
        .from("schedule_entries")
        .update({
          position_id: data.position_id,
          start_time: data.start_time,
          end_time: data.end_time,
          shift_template_id: data.shift_template_id,
          notes: data.notes || null,
        })
        .eq("id", dialogEntry.id);

      if (error) {
        toast.error(translateDbError(error.message, "Error al actualizar el turno"));
      } else {
        toast.success("Turno actualizado");
        setDialogOpen(false);
        fetchScheduleData();
      }
    } else {
      // Create new
      const { error } = await supabase.from("schedule_entries").insert({
        schedule_id: schedule.id,
        employee_id: dialogEmployeeId,
        date: dialogDate,
        position_id: data.position_id,
        start_time: data.start_time,
        end_time: data.end_time,
        shift_template_id: data.shift_template_id,
        notes: data.notes || null,
      });

      if (error) {
        toast.error(translateDbError(error.message, "Error al crear el turno"));
      } else {
        toast.success("Turno asignado");
        setDialogOpen(false);
        fetchScheduleData();
      }
    }

    setSaving(false);
  }

  // Delete entry
  async function handleDeleteEntry() {
    if (!dialogEntry) return;
    setSaving(true);

    const { error } = await supabase
      .from("schedule_entries")
      .delete()
      .eq("id", dialogEntry.id);

    if (error) {
      toast.error(translateDbError(error.message, "Error al eliminar el turno"));
    } else {
      toast.success("Turno eliminado");
      setDialogOpen(false);
      fetchScheduleData();
    }

    setSaving(false);
  }

  // Build entry map for grid
  const entryMap = buildEntryMap(entries);
  const dates = getMonthDates(year, month);

  // Find employee name for dialog
  const dialogEmployee = employees.find((e) => e.id === dialogEmployeeId);
  const dialogEmployeeName = dialogEmployee
    ? `${dialogEmployee.first_name} ${dialogEmployee.last_name}`
    : "";
  const dialogDateLabel = dialogDate
    ? new Date(dialogDate + "T00:00:00").toLocaleDateString("es-ES", {
        weekday: "long",
        day: "numeric",
        month: "long",
      })
    : "";

  // Loading state
  if (authLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  // Employee view: show only published schedules with their entries
  if (isEmployee) {
    const myEntries = entries.filter(
      (e) => e.employee_id === user?.id
    );

    return (
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold">Mis horarios</h1>
          <p className="text-muted-foreground">
            Tu calendario de turnos publicados
          </p>
        </div>

        {/* Location + month nav for employees too */}
        <ScheduleToolbar
          locations={locations}
          selectedLocationId={selectedLocationId}
          onLocationChange={setSelectedLocationId}
          month={month}
          year={year}
          onPrevMonth={handlePrevMonth}
          onNextMonth={handleNextMonth}
          scheduleStatus={schedule?.status || null}
          onCreateDraft={() => {}}
          onPublish={() => {}}
          onArchive={() => {}}
          isAdmin={false}
          isManager={false}
          saving={false}
        />

        {schedule?.status === "published" || schedule?.status === "archived" ? (
          <EmployeeScheduleView
            entries={myEntries}
            month={month}
            year={year}
            loading={loading}
          />
        ) : (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <p className="text-muted-foreground">
              No hay horario publicado para {MONTHS[month]} {year}.
            </p>
          </div>
        )}
      </div>
    );
  }

  // Admin / Manager view
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Horarios</h1>
        <p className="text-muted-foreground">
          Gestiona los horarios mensuales por sede
        </p>
      </div>

      <ScheduleToolbar
        locations={locations}
        selectedLocationId={selectedLocationId}
        onLocationChange={setSelectedLocationId}
        month={month}
        year={year}
        onPrevMonth={handlePrevMonth}
        onNextMonth={handleNextMonth}
        scheduleStatus={schedule?.status || null}
        onCreateDraft={handleCreateDraft}
        onPublish={handlePublish}
        onArchive={handleArchive}
        onAutoGenerate={() => setAutoGenOpen(true)}
        isAdmin={isAdmin}
        isManager={isManager}
        saving={saving}
      />

      {loading ? (
        <div className="flex items-center justify-center py-12">
          <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
        </div>
      ) : !schedule ? (
        <div className="flex flex-col items-center justify-center py-16 text-center rounded-md border bg-card">
          <p className="text-muted-foreground mb-2">
            No hay horario para {MONTHS[month]} {year}.
          </p>
          {canManage && selectedLocationId && (
            <p className="text-sm text-muted-foreground">
              Crea un borrador para comenzar a asignar turnos.
            </p>
          )}
        </div>
      ) : (
        <>
          {/* Export button when schedule has entries */}
          {entries.length > 0 && (
            <div className="flex justify-end">
              <ExportDropdown
                entries={entries}
                employees={employees}
                month={month}
                year={year}
                locationName={locations.find((l) => l.id === selectedLocationId)?.name || ""}
              />
            </div>
          )}
          <ScheduleCalendarGrid
            dates={dates}
            employees={employees}
            entryMap={entryMap}
            canEdit={canManage && schedule.status === "draft"}
            onCellClick={handleCellClick}
          />
        </>
      )}

      {/* Auto-generate dialog */}
      {schedule && (
        <AutoGenerateDialog
          open={autoGenOpen}
          onOpenChange={setAutoGenOpen}
          schedule={schedule}
          employees={employees}
          shiftTemplates={shiftTemplates}
          positions={positions}
          existingEntries={entries}
          month={month}
          year={year}
          locationName={locations.find((l) => l.id === selectedLocationId)?.name ?? ""}
          onGenerated={fetchScheduleData}
        />
      )}

      {/* Assign dialog */}
      <ShiftAssignDialog
        open={dialogOpen}
        onOpenChange={setDialogOpen}
        entry={dialogEntry}
        employeeName={dialogEmployeeName}
        dateLabel={dialogDateLabel}
        positions={positions}
        shiftTemplates={shiftTemplates}
        saving={saving}
        onSave={handleSaveEntry}
        onDelete={handleDeleteEntry}
      />
    </div>
  );
}
